# Generated by Django 3.2.25 on 2025-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='specialties',
            field=models.TextField(choices=[('fittnes', 'Fittnes'), ('bodybuliding', 'Body Building')]),
        ),
    ]
