# Generated by Django 3.2.25 on 2025-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coachprofile_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='coach_profiles/')),
                ('specialties', models.TextField(choices=[('fittnes', 'Fittnes'), ('bodybuliding', 'Body Building')])),
                ('certification', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('view_own_profile', 'Can view own coach profile'), ('edit_own_profile', 'Can edit own coach profile'), ('view_clients', 'Can view assigned clients'), ('manage_clients', 'Can manage assigned clients'), ('create_workouts', 'Can create workout plans'), ('edit_workouts', 'Can edit workout plans')],
            },
        ),
        migrations.RemoveField(
            model_name='coachprofile',
            name='user',
        ),
    ]
