# Generated by Django 3.2.25 on 2025-07-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250707_1448'),
        ('users', '0003_auto_20250707_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachProfile',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='core.gym'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
