# Generated by Django 3.2.25 on 2025-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_coachprofile_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_level', models.CharField(choices=[('begginer', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coachprofile')),
            ],
        ),
    ]
