# Generated by Django 3.2.25 on 2025-07-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerrating',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='programrating',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.trainingprograms'),
        ),
        migrations.AlterUniqueTogether(
            name='trainerrating',
            unique_together={('trainer', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='programrating',
            unique_together={('program', 'ip_address')},
        ),
    ]
