# Generated by Django 3.2.25 on 2025-06-03 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprograms',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coachprofile'),
        ),
    ]
