# Generated by Django 3.2.25 on 2025-07-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coachprofile_specialties'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprograms',
            name='image',
            field=models.ImageField(upload_to='training_programs/'),
        ),
        migrations.CreateModel(
            name='TrainerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.coachprofile')),
            ],
            options={
                'unique_together': {('trainer', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='ProgramRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.trainingprograms')),
            ],
            options={
                'unique_together': {('program', 'ip_address')},
            },
        ),
    ]
