# Generated by Django 3.2.25 on 2025-07-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250707_1448'),
        ('users', '0003_auto_20250707_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerrating',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.trainerprofile'),
        ),
        migrations.AlterField(
            model_name='trainingprograms',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainerprofile'),
        ),
    ]
